apiVersion: v1
kind: ConfigMap
metadata:
  name: gassistant-config
  labels:
    app.kubernetes.io/name: "google-assistant-telegram-bot"
    app.kubernetes.io/instance: "google-assistant-telegram-bot-live"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: "config"
    app.kubernetes.io/part-of: "google-assistant-telegram-bot"
    app.kubernetes.io/managed-by: "argo"
data:
  config.js: >
    module.exports.telegramBotToken =
    '<path:kv/data/tg-bots/google-assistant#botToken>';

    module.exports.debug = false; 

    module.exports.adminChats = ['<path:kv/data/tg-bots/google-assistant#admin-1-id>']; 

    module.exports.admins = [<path:kv/data/tg-bots/google-assistant#admin-1-id>]; 

    module.exports.port = process.env.PORT || 443; 

    module.exports.host = '0.0.0.0'; 
