apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccnet-gassistant-bot-tg
  labels:
    app: ccnet-gassistant-bot
    app.kubernetes.io/name: "google-assistant-telegram-bot"
    app.kubernetes.io/instance: "google-assistant-telegram-bot-live"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: "server"
    app.kubernetes.io/part-of: "google-assistant-telegram-bot"
    app.kubernetes.io/managed-by: "argo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccnet-gassistant-bot
  template:
    metadata:
      labels:
        app: ccnet-gassistant-bot
    spec:
      containers:
        - name: ccnet-gassistant-bot
          image: itachi1706/personal-docker-images:gassist-tg-bot
          resources:
            limits:
              cpu: 10m
              memory: 150Mi
            requests:
              cpu: 1m
              memory: 50Mi
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub-creds
