apiVersion: v1
kind: Secret
metadata:
  name: gassistant-google-config
  labels:
    app.kubernetes.io/name: "google-assistant-telegram-bot"
    app.kubernetes.io/instance: "google-assistant-telegram-bot-live"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: "secrets"
    app.kubernetes.io/part-of: "google-assistant-telegram-bot"
    app.kubernetes.io/managed-by: "argo"
  annotations:
    avp.kubernetes.io/path: 'kv/data/tg-bots/google-assistant'
stringData:
  credentials-secure_google.json: >-
    <google-secure-creds>
  credentials.json: >-
    <creds>
  credentials_google.json: >-
    <google-creds>
type: Opaque
