apiVersion: v1
kind: Secret
metadata:
  name: gassistant-google-config
  annotations:
    avp.kubernetes.io/path: 'kv/data/tg-bots/google-assistant'
data:
  credentials-secure_google.json: >-
    <google-secure-creds>
  credentials.json: >-
    <creds>
  credentials_google.json: >-
    <google-creds>
type: Opaque
